#!/usr/bin/env bash

me=$(basename "$0")

case "$1" in

  'build')
    echo ""
    echo "Building"
    echo ""
    ./gradlew build
    ;;

  'clean')
    echo ""
    echo "Cleaning"
    echo ""
    ./gradlew clean
    ;;

  'test')
    echo ""
    echo "Running tests"
    echo ""
    ./gradlew clean check
    ;;

  'gradle:upgrade')
    echo ""
    echo "Upgrading gradle."
    echo ""
    if [ -z "$2" ]; then
      echo "Version not specified!"
    else
      ./gradlew wrapper --gradle-version $2 --distribution-type=all
    fi
    echo ""
    ;;

  'report:test:open')
    echo ""
    echo "Opening Junit test report."
    echo ""
    open ./app/build/reports/tests/test/index.html
    open ./app/build/reports/tests/integrationTest/index.html
    open ./app/build/reports/tests/sampleTestType/index.html
    echo ""
    ;;

  *)
    echo -e ""
    echo "Usage:"
    echo ""
    echo "$(tput setaf 5)    $me$(tput sgr0) $(tput setaf 3)<command>$(tput sgr0)"
    echo ""
    echo "Commands:"
    echo ""

    echo "$(tput setaf 3)    build                                      $(tput sgr0)      Build application"
    echo "$(tput setaf 3)    clean                                      $(tput sgr0)      Delete generated and temporary files"
    echo "$(tput setaf 3)    test                                       $(tput sgr0)      Run tests"
    echo "$(tput setaf 3)    gradle:upgrade <version>                   $(tput sgr0)      Upgrade gradle"
    echo "$(tput setaf 3)    report:test:open                           $(tput sgr0)      Open junit test reports for all modules"

esac
