/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppIntegrationTest {
    @Test
    fun appHasAGreeting1a() {
        println("AppIntegrationTest 1a")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun appHasAGreeting1b() {
        Out.print("AppIntegrationTest 1b")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun appHasAGreeting1c() {
        Out.print("AppIntegrationTest 1c")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
