/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppSlowTest1 {
    @Test
    fun AppSlowTest1_appHasAGreeting1a() {
        println("appHasAGreeting 1a")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun AppSlowTest1_appHasAGreeting1b() {
        println("appHasAGreeting 1b")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun AppSlowTest1_appHasAGreeting1c() {
        println("appHasAGreeting 1c")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
